name: ctf_clicker
description: "Task for SurCTF"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.20.2
  build_runner: ^2.4.12
  path: ^1.9.0
  path_provider: ^2.1.4

  salomon_bottom_bar: ^3.3.2
  simple_progress_indicators: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.3

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/png/emoji/